### ISSUE TITLE
Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by jpike88** [gx0r/brute-knex#7]
Getting the above error occasionally.

`insert into `api_brute_force` (`count`, `firstRequest`, `key`, `lastRequest`, `lifetime`) values (1, '2019-01-27 05:46:16.662', 'XQzdBFApWa3E5g5IVMAJmMheI7E6jtHoRj0Diw+Yl4k=', '2019-01-27 05:46:16.662', '2019-01-27T05:46:26.669Z')`

**Comment by kirrg001** [comment]
@jpike88 Could you please provide more context and information?

**Comment by jpike88** [comment]
```
Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
at Query.Sequence._packetToError (/var/app/current/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
at Query.ErrorPacket (/var/app/current/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
at Protocol._parsePacket (/var/app/current/server/node_modules/mysql/lib/protocol/Protocol.js:278:23)
at Parser.write (/var/app/current/server/node_modules/mysql/lib/protocol/Parser.js:76:12)
at Protocol.write (/var/app/current/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
at Socket.<anonymous> (/var/app/current/server/node_modules/mysql/lib/Connection.js:91:28)
at Socket.<anonymous> (/var/app/current/server/node_modules/mysql/lib/Connection.js:502:10)
at Socket.emit (events.js:182:13)
at Socket.EventEmitter.emit (domain.js:442:20)
at addChunk (_stream_readable.js:283:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
--------------------
at Protocol._enqueue (/var/app/current/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
at Connection.query (/var/app/current/server/node_modules/mysql/lib/Connection.js:200:25)
at /var/app/current/server/node_modules/knex/lib/dialects/mysql/index.js:154:18
at Promise._execute (/var/app/current/server/node_modules/bluebird/js/release/debuggability.js:303:9)
at Promise._resolveFromExecutor (/var/app/current/server/node_modules/bluebird/js/release/promise.js:483:18)
at new Promise (/var/app/current/server/node_modules/bluebird/js/release/promise.js:79:10)
at Client_MySQL._query (/var/app/current/server/node_modules/knex/lib/dialects/mysql/index.js:148:12)
at Client_MySQL.query (/var/app/current/server/node_modules/knex/lib/client.js:202:17)
at /var/app/current/server/node_modules/knex/lib/transaction.js:272:21
at tryCatcher (/var/app/current/server/node_modules/bluebird/js/release/util.js:16:23)
at Function.Promise.attempt.Promise.try (/var/app/current/server/node_modules/bluebird/js/release/method.js:39:29)
at Client_MySQL.trxClient.query (/var/app/current/server/node_modules/knex/lib/transaction.js:269:34)
at Runner.<anonymous> (/var/app/current/server/node_modules/knex/lib/runner.js:146:36)
at Runner.tryCatcher (/var/app/current/server/node_modules/bluebird/js/release/util.js:16:23)
at Runner.query (/var/app/current/server/node_modules/bluebird/js/release/method.js:15:34)
at /var/app/current/server/node_modules/knex/lib/runner.js:48:21
at tryCatcher (/var/app/current/server/node_modules/bluebird/js/release/util.js:16:23)
at /var/app/current/server/node_modules/bluebird/js/release/using.js:185:26
at tryCatcher (/var/app/current/server/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/var/app/current/server/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/var/app/current/server/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/var/app/current/server/node_modules/bluebird/js/release/promise.js:614:10)
```

**Comment by jpike88** [comment]
On node 10.13.0, using mySQL 5.7 (on aws aurora).

Happens occasionally on a request

**Comment by kirrg001** [comment]
Deadlocks can happen with brute-knex if you don't use it correctly. How do you use brute-knex?

**Comment by jpike88** [comment]
As middleware for a JSON-RPC server... code looks like this

```
function getToken(request) {
	if (
		request.body &&
		Array.isArray(request.body.params) &&
		typeof request.body.params[0] === 'string' &&
		request.body.params[0].length === 40
	) {
		return request.body.params[0];
	}
	return null;
}

		const store = new BruteKnex({
			tablename: 'api_brute_force',
			knex: sql.knex
		});

		const userBruteforce = new ExpressBrute(store, {
			freeRetries: 100, // 100 attempts
			minWait: 30, // penalty starts at 30 seconds
			maxWait: 60 * 60 * 1000 * 24, // penalty ramps up to 24 hours
			lifetime: 10 // 10 seconds lifetime (100 attempts allowed within 10 seconds)
		});

		app.use(userBruteforce.getMiddleware({
			key: (req, _, next) => {
				// prevent too many attempts for the same access token
				if (getToken(req) != null) {
					next(req.body.params[0]);
				} else {
					next(req.ip);
				}
			}
		}));
```

**Comment by kirrg001** [comment]
Deadlocks usually happen with brute-knex if your brute table is empty and two transactions/requests are coming in.

e.g. https://bugs.mysql.com/bug.php?id=48911

**Comment by jpike88** [comment]
wow wtf. is it worth this library keeping a 'dummy' row in there to avoid this?
